# Generated by Django 5.2.7 on 2025-10-10 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfidSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=32)),
                ('label_snapshot', models.CharField(blank=True, help_text='Copie du label au début', max_length=100)),
                ('authorisation', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('volume_start_ml', models.FloatField(default=0.0)),
                ('volume_end_ml', models.FloatField(default=0.0)),
                ('volume_delta_ml', models.FloatField(default=0.0)),
                ('last_message', models.TextField(blank=True, default='')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='controlvanne.card')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
