# Generated by Django 5.2.7 on 2025-10-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0002_rfidsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfidsession',
            old_name='authorisation',
            new_name='authorized',
        ),
    ]
