# Generated by Django 5.2.7 on 2025-10-11 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0003_rename_authorisation_rfidsession_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identifiant technique: ex. 'froid', 'chaud'", unique=True)),
                ('liquid_label', models.CharField(default='Liquide', help_text='Nom affiché du liquide', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='rfidsession',
            name='liquid_label_snapshot',
            field=models.CharField(blank=True, help_text='Copie du nom du liquide au début', max_length=100),
        ),
        migrations.AddField(
            model_name='rfidsession',
            name='dispenser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='controlvanne.dispenser'),
        ),
    ]
