# Generated by Django 5.2.7 on 2025-10-15 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0004_dispenser_rfidsession_liquid_label_snapshot_and_more'),
    ]

    operations = [
        migrations.RenameModel('Dispenser', 'TireuseBec'),
        migrations.RenameField('rfidsession', 'dispenser', 'tireuse_bec'),
    ]