# Generated by Django 5.2.7 on 2025-10-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0006_fill_tireuse_bec_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidsession',
            name='tireuse_bec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='controlvanne.tireusebec'),
        ),
        migrations.AlterField(
            model_name='tireusebec',
            name='slug',
            field=models.SlugField(help_text="Identifiant technique: ex. 'Biere', 'soft'", unique=True),
        ),
    ]
