# Generated by Django 5.2.7 on 2025-10-16 11:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0007_alter_rfidsession_tireuse_bec_alter_tireusebec_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solde en unité (ex: patate)', max_digits=12),
        ),
        migrations.AddField(
            model_name='rfidsession',
            name='allowed_ml_session',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='rfidsession',
            name='charged_units',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='rfidsession',
            name='unit_label_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rfidsession',
            name='unit_ml_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='tireusebec',
            name='unit_label',
            field=models.CharField(default='patate', help_text="Nom de l'unité de solde (ex: patate)", max_length=20),
        ),
        migrations.AddField(
            model_name='tireusebec',
            name='unit_ml',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Millilitres par unité (ex: 100.00 ml = 10 cL)', max_digits=8),
        ),
    ]
