# Generated by Django 5.2.7 on 2025-10-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlvanne', '0008_card_balance_rfidsession_allowed_ml_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tireusebec',
            name='agent_base_url',
            field=models.CharField(blank=True, default='http://192.168.1.56:5000', help_text="URL de l'agent Flask sur le Pi (ex: http://pi:5000)", max_length=200),
        ),
    ]
